theme: minima
permalink: pretty
title: SMS Backup+
description: open-source backup app for Android, supports SMS / MMS / call logs
author: Jan Berkel
github_username: jberkel
twitter_username: jberkel
google_analytics: UA-106148913-1
header_pages:
  - privacy-policy.md

exclude:
  - Gemfile
  - Gemfile.lock
